#!/usr/bin/python3
import glob
import io
import os
import requests
import subprocess
import sys
import zipfile
from KattisCLI import submit as kattisSubmit

LANG_MAP = {
	"c": "#include <stdio.h>\n\nint main()\n{\n\t\n\treturn 0;\n}\n",
	"c++": "#include <iostream>\n\nusing namespace std;\n\nint main()\n{\n\t\n\treturn 0;\n}\n",
	"python": "import sys\n\n"
}

LANG_EXT = {
	"c": ".c",
	"c++": ".cpp",
	"python": ".py"
}

EXEC_MAP = {
	".c":   ["./a.out"],
	".cpp": ["./a.out"],
	".py":  ["python3", "{1}"]
}

EXT_MAP = {
	".c":   [".c", ".h"],
	".cpp": [".cpp", ".h"],
	".py":  [".py"]
}

URL = "https://open.kattis.com/problems/"

def trim(arr):
	while arr and not arr[0]:
		arr.pop(0)
	while arr and not arr[-1]:
		arr.pop()
	return arr


def init(args):
	"""Download a problem and sample data from Kattis"""

	if len(args) < 2:
		usage(1)
		return 1

	problem, lang = args[0].lower(), args[1].lower()
	sampleData = True

	if lang not in LANG_MAP:
		print("'" + lang + "' is not a valid language. Available languages: "
	          + ", ".join(list(LANG_MAP.keys())))
		return 1

	try:
		r = requests.get(URL + problem + "/file/statement/samples.zip", stream=True)
		z = zipfile.ZipFile(io.BytesIO(r.content))
	except:
		if requests.get(URL + problem).status_code == 200:
			sampleData = False
		else:
			print("Unable to find problem \"" + problem + '"')
			return 1

	if not os.path.exists("problems/" + problem):
		os.mkdir("problems/" + problem)

	if not os.path.exists("problems/" + problem + "/samples"):
		os.mkdir("problems/" + problem + "/samples")

	if sampleData:
		samplePath = "problems/" + problem + "/samples/"
		z.extractall(samplePath)
		files = sorted(os.listdir(samplePath))
		for i in range(0, len(files)//2):
			for j in range(2):
				name, ext = os.path.splitext(files[2*i+j])
				os.rename(
					"{}{}{}".format(samplePath, name, ext),
					"{}{}{}".format(samplePath, i+1, ext)
				)

	fileName = "problems/" + problem + "/" + problem + LANG_EXT[lang]
	f = open(fileName, "w")
	f.write(LANG_MAP[lang])
	f.close()

	subprocess.Popen(["code", "-a", fileName])


def submit(args):
	"""Submit a problem to Kattis"""

	if len(args) < 1:
		usage(3)
		return 1

	problem = args[0].lower()

	try:
		mainFile = glob.glob("./problems/" + problem + "/" + problem + ".*")[0]
		name, ext = os.path.splitext(mainFile)
		if ext not in EXEC_MAP:
			raise Exception("No source code found!")
	except Exception as e:
		print(e)
		print("Error: No source code found!")
		return 1

	path = os.path.dirname(mainFile)
	name = os.path.basename(mainFile)
	files = [mainFile]
	for file in glob.glob("./problems/" + problem + "/*"):
		if file != mainFile:
			fileName, fileExt = os.path.splitext(file)
			if fileExt in EXT_MAP[ext]:
				files.append(file)
	kattisSubmit.main(["-p", problem, *files])


def execute(path, script, ext, sample = None):
	cmd = [part.format(path, script) for part in EXEC_MAP[ext]]
	stdout = stderr = ""
	try:
		p = subprocess.Popen(cmd, cwd=path, stdin=subprocess.PIPE,
								stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		if sample:
			with open(sample, 'rb') as f:
				stdout, stderr = p.communicate(f.read(), 5)
		else:
			stdout, stderr = p.communicate(timeout=5)

	except subprocess.TimeoutExpired:
		print("Took too long!")
		return False, stdout + stderr
	except subprocess.SubprocessError:
		print("Runtime error")
		return False, stdout + stderr
	if stderr:
		print("Runtime error")
		return False, stdout + stderr

	return True, stdout + stderr


def test(args):
	"""Test your program against all of the sample data (won't work with variable answers)"""
	if len(args) < 1:
		usage(2)
		return 1

	problem = args[0].lower()

	if not os.path.exists("./problems/" + problem):
		print("Problem '{}' does not exist".format(problem))
		return 1

	search = args[1] if len(args) >= 2 else '*'
	inSamples = glob.glob("./problems/" + problem + "/samples/{}.in".format(search))
	outSamples = glob.glob("./problems/" + problem + "/samples/{}.ans".format(search))
	verbose = len(args) >= 2 and args[-1] == "-v"

	inSamples.sort()
	outSamples.sort()

	# Locate the problem source file
	try:
		script = glob.glob("./problems/" + problem + "/" + problem + ".*")[0]
		source, ext = os.path.splitext(script)
		if ext not in EXEC_MAP:
			raise Exception("No source code found")
	except Exception as e:
		return 1
	source = os.path.basename(script)
	path = os.path.dirname(script)
	results = [False]*len(inSamples)

	# Check if the samples are available, execute if none
	if len(inSamples) == 0:
		if search == '*':
			result, output = execute(path, source, ext)
			print(output.decode().strip())
			return 0
		else:
			print("No sample file '" + search + "'")
		return 1

	# Execute the program with each sample
	for i, value in enumerate(inSamples):
		result, output = execute(path, source, ext, value)
		if result is False:
			print(output.decode())
			continue
		print("Test #{}:\n".format(i+1))
		linesA = trim(list(output.decode().split('\n')))
		with open(outSamples[i]) as f:
			linesB = f.readlines()
		result = True
		for j in range(len(linesA)):
			print("    ", linesA[j].strip())
			if len(linesA) <= len(linesB) and linesA[j].strip() != linesB[j].strip():
				result = False
		results[i] = result and len(linesA) == len(linesB)
		if results[i]:
			print("\nResult: Accepted\n\n")
			continue
		print("\nResult: Wrong answer\n\n")

	if results.count(True) == len(results):
		print("Success!", end="")
	else:
		print("Failed!", end="")
	print(" {}/{} tests passed".format(results.count(True), len(results)))


commands = {
	'init': init,
	"submit": submit,
	'test': test
}

def usage(id = 0):
	if id == 0:
		print("Usage: kattis <command> [arguments] [options]\n")
		print("Commands:")
		for command in sorted(commands.keys()):
			print("\t{}\t{}".format(command, commands[command].__doc__))
	elif id == 1:
		print("Usage: kattis init <problem id> <language(c, c++, python)> [options]\n")
		print("Languages:")
		for lang in sorted(LANG_MAP.keys()):
			print("\t" + lang)
	elif id == 2:
		print("Usage: kattis test <problem id> [sample id]")
	elif id == 3:
		print("Usage: kattis submit <problem id>")


def main(argv):

	if len(argv) < 2 or argv[1] not in commands:
		usage()
		return 1
	else:
		return commands[argv[1]](argv[2:])


if __name__ == '__main__':
	sys.exit(main(sys.argv))
